services:
  - type: postgres
    name: postgres-database
    plan: free  # Use "free" for the free tier or "starter" for paid plans
    envVars:
      - key: POSTGRES_DB
        value: ${POSTGRES_DB}
      - key: POSTGRES_USER
        value: ${POSTGRES_USER}
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
    volume:
      name: postgres_data
      mountPath: /var/lib/postgresql/data

  - type: web
    name: webapi
    env: dotnet
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: API__ConnectionStrings__DatabaseConnection
        value: Host=postgres-database:5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    port: 8080  # Expose the primary port
    depends_on:
      - postgres-database

  - type: web
    name: frontend
    env: node
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    envVars:
      - key: ENV_KEY
        value: ${ENV_VALUE}
    port: 3000
    depends_on:
      - webapi